🚀 1단계 - DI 컨테이너 구현하기, 🚀 2단계 - DI 컨테이너 구현하기(힌트)
next-step/java-di pull request #36
Opened 2024-08-17 04:51 UTC by jivebreaddev

## 테스트 
![image](https://github.com/user-attachments/assets/ed5eff4d-c9c1-4330-babc-f1a0678f5630)
![image](https://github.com/user-attachments/assets/3dbf81c6-4eab-451e-b0ee-5cfb1eedd573)

## 요구사항 정리
- [] 요구사항 1 - DefaultListableBeanFactoryTest 가 통과하게 만든다.
    - @Controller, @Service, @Repository를 스캔해서 클래스들을 가져온다. (BeanScanner)
      - 기능 
      - 조건 
    - @Autowired을 사용한 생성자를 이용해서 의존관계를 생성한다. (BeanFactory)
      - 기능
      - 조건
- [] 요구사항 2 - AnnotationMapping이 동작하도록 리팩터링한다.
    - BeanFactory와 BeanScanner를 잘 활용해서 동작하면 된다.
      
- [] 공통 요구사항
  - [] DefaultListableBean이 Bean 조립 즉, Injection을 책임으로 가진 구현체이다. 책임에 맞게 클래스 설계하라 
    - doResolveDependency(Dependency-descriptor, beanName)  (의존 관계에 대한 descriptor, bean 이름을 가지고 주입해준다.)
      - findAutowireCandidates(qualifier를 가지고 주입하게된다.)
      - ConstructorResolver를 통해 injectionPoint를 가지고 bean 주입을 하게된다. 
  - [] BeanScanner 는 Bean을 scan 만하는 책임을 가진다.
  - [] BeanDefinitionRegistry 에서 bean을 등록하는 책임을 가진다. (BeanDefinitionMap에 넣어준다. beanName, beanDefinition)
  - [] BeanDefinition은 instance 에 대한 정보를 담는다 + scope

## 구현 내용 정리
- 호출 순서
    - ApplicationContext -> DefaultListableBeanFactory(Scanner)
    - scaner 호출로 registry에 bean definition 등록
    - beanfactory.initialize로 객체들 definition에 맞게 구현체 생성
    - ApplicationContext 반환
- DefaultListableBean (BeanDefinitionRegistry 인터페이스, BeanFactory 인터페이스)
  - beanDefinitionMap (beanName, beanDefinition) 해쉬맵
  - singletonObjects (clazz, 구현체들) 해쉬맵
- 라이프사이클
  - REGISTRY 등록 
  - initialize 하면 Registry에서 BeanDefinition을 읽어서 instance 생성하는 방향이다.
    - injector를 확인해보고 다른 의존관계를 getBean으로 가져오는데 없다면 생성하면 된다.

2024-08-18 07:01 UTC, sah3122 requested changes
DI컨테이너 구현 잘해주셨습니다 👍 
사소한 질문 남겨두었는데 다음 미션을 진행하기전 확인 부탁드려요 😄

2024-08-18 07:01 UTC, sah3122 commented on README.md
> +## 1단계 요구사항
요구사항 정리 잘해주셨습니다 👍

2024-08-18 07:01 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/support/injector/ConstructorInjector.java
> +        return constructor != null;
생성자가 존재하는것만 체크하기 보단 이번 미션에서의 예시 처럼 @Autowired 를 검사하는것도 좋을것 같습니다 😄

2024-08-18 07:01 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +            .collect(Collectors.toSet());
`com.interface21.context`라는 패키지를 기준으로 Component 어노테이션의 위치를 찾고 아래 로직을 통해 basePackage를 기준으로 registry에 등록하는 로직을 분리해주신것 같은데 이와 같이 분리해주신 이유가 궁금합니다 😄

2024-08-18 07:01 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/support/injector/InjectorConsumerConfig.java
> +        Constructor<? extends Constructor> constructor, Set<Field> fields) {
fields 를 전달 받는 이유가 있을까요 ?

2024-08-18 07:01 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/config/DefaultBeanDefintion.java
> +            .orElse(new DefaultInjector(bean));
DefaultInjector 를 매번 생성하지 않고 전달해줄수 있지 않을까요 ?

2024-08-18 07:01 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/support/injector/InjectorConsumer.java
> +public interface InjectorConsumer<T> {
빈 주입을 위한 인터페이스 분리 잘해주셨습니다 😄

2024-08-18 09:56 UTC, jivebreaddev commented on README.md
> +## 1단계 요구사항
칭찬 감사합니다!~

2024-08-18 09:59 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +            .collect(Collectors.toSet());
앗, 저 로직은 registry에 등록하는 로직이 아닙니다!

`@Controller, @Service, @Repository`들은 `@Component`를  공통으로 가지고 있고, 이에 따라,`@Component` 값을 가지고 있는 애노테이션들을 스캔해서 가지고오는 코드입니다.

제가 메서드 분리로 조금 명시적으로 표현을 하겠습니다!

2024-08-18 09:59 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/support/injector/InjectorConsumerConfig.java
> +        Constructor<? extends Constructor> constructor, Set<Field> fields) {
필드 주입도 구현하려고하다가 생성자 주입만 진행을 했습니다.

2024-08-18 10:04 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/support/injector/InjectorConsumerConfig.java
> +        Constructor<? extends Constructor> constructor, Set<Field> fields) {
변경해두겠습니다!

2024-08-18 10:37 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/support/injector/ConstructorInjector.java
> +        return constructor != null;
생성시에 @Autowired를 검사하는 로직이 있어서 Injector의 명시적 조건이 누락이 되었네요!

가독성과 논리적으로 이해하기 편한것 같습니다!

2024-08-18 10:38 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/support/injector/ConstructorInjector.java
> +        return constructor != null;
![image](https://github.com/user-attachments/assets/a6d23e19-89af-441f-8d11-172e401dad95)

2024-08-18 10:39 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +            .collect(Collectors.toSet());
![image](https://github.com/user-attachments/assets/116bf532-8cc0-45fa-877e-f25dfffc5aec)

2024-08-18 10:44 UTC, jivebreaddev commented on di/src/main/java/com/interface21/beans/factory/config/DefaultBeanDefintion.java
> +            .orElse(new DefaultInjector(bean));
아.. 좋지 않은 코드였네요! 감사합니다!~


![image](https://github.com/user-attachments/assets/b8e3ee58-53ba-44f9-97bc-57f1b0801176)

2024-08-19 09:00 UTC, sah3122 approved these changes
1, 2단계 미션을 한번에 진행해주셨는데 한번에 두가지 미션을 완료처리 할수 없기때문에 2단계 미션에 대한 PR요청 주시면 머지 하도록 하겠습니다 😄 
한가지 코멘트 남겨두었는데 확인 부탁드려요 !

2024-08-19 09:00 UTC, sah3122 commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +            .collect(Collectors.toSet());
코멘트의 의도는 아래 로직을 통해 작업을 하나로 합칠수 있지 않을까 했는데 분리해주신 이유를 질문 드렸던것 입니다 😄 
```java
Reflections beanScanner = new Reflections(basePackage);
        for (Class<?> subType : annotations) {
            beanScanner.getTypesAnnotatedWith((Class<? extends Annotation>) subType)
                .stream()
                .forEach(component -> registry.registerBeanDefinition(component,
                    new DefaultBeanDefintion(component)));
        }
```

2024-08-19 09:00 UTC, merged