🚀 3단계 - @Configuration 구현하기
next-step/java-di pull request #45
Opened 2024-08-24 11:36 UTC by heedoitdox

안녕하세요 선흠님! 

크게 아래 기능 위주로 구현했습니다!
- ConfigurationBeanScanner 를 추가하여 @ComponentScan 의 basePackages 범위 내의 @Configuration 클래스들을 스캔하고 @Bean 애노테이션이 붙은 메서드들의 리턴타입이 싱글톤 빈으로 등록될 수 있도록 구현했습니다.

요새 갑자기 회사일이 바빠져서 뜨문뜨문 작업하다보니 했던 부분이 잘 기억이 안나서 좀 오래걸렸네요 ㅠㅠ

2024-08-25 14:28 UTC, shared-moon requested changes
영빈님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
몇가지 코멘트를 남겨 뒀는데, 다음 미션 진행 전 생각해보면 좋을 것 같아요!
피드백 확인 후 리뷰 재요청 부탁드려요!

2024-08-25 14:28 UTC, shared-moon commented on di/src/main/java/com/interface21/context/support/AnnotationConfigWebApplicationContext.java
> +        ConfigurationBeanScanner configurationBeanScanner = new ConfigurationBeanScanner(configurationClasses);
요거 밑에서 재사용해도 될 것 같아요 ~

근데 ConfigurationBeanScanner랑 BeanScanner가 각각 독립적인 객체인데 한쪽에서 만들어진 정보에 의존해서 동작하는게 조금 어색해 보이네요! 차라리 베이스 패키지 얻는 부분을 따로 빼고 각각 베이스패키지를 받아서 만들어지도록 하면 어떨까요 ?

2024-08-25 14:28 UTC, shared-moon commented on di/src/main/java/com/interface21/context/support/AnnotationConfigWebApplicationContext.java
> +        Map<Class<?>, BeanDefinition> configurationBeanDefinitionMap = new ConfigurationBeanScanner(configurationClasses).scan();
쓰는게 scan() 밖에 없어서, 이러면 굳이 객체 생성을 해야할까 라는 생각도 드네요!

2024-08-25 14:28 UTC, shared-moon commented on di/src/main/java/com/interface21/beans/factory/config/GenericBeanDefinition.java
> +  public String getBeanName() {
`@Override` 된 메서드들이 위에 위치하는게 어떨까요 ?

2024-08-25 14:28 UTC, shared-moon commented on di/src/main/java/com/interface21/beans/factory/config/GenericBeanDefinition.java
> +  private final String beanName;
요거 ConfigurationBeanDefinition이랑 역할은 같은데 변수명이 달라서 조금 헷갈리는거같아요!

2024-08-25 14:28 UTC, shared-moon commented on di/src/main/java/com/interface21/beans/factory/support/SimpleBeanDefinitionRegistry.java
> +    Arrays.stream(maps).forEach(beanDefinitionMap::putAll);
요거 이렇게되면 BeanScanner랑 ConfigurationBeanScanner로 읽은 것 중에 beanName이 같은애들은 그냥 덮어씌워져서 문제가 발생했을 때 모르고 지나갈 수 있지 않을까요 ?

2024-08-25 16:06 UTC, heedoitdox commented on di/src/main/java/com/interface21/context/support/AnnotationConfigWebApplicationContext.java
> +        ConfigurationBeanScanner configurationBeanScanner = new ConfigurationBeanScanner(configurationClasses);
앗 좋습니다!! 
순서대로 생각했을 땐 이상함을 느끼지 못했었는데 결국 행위는 같으니 베이스패키지를 받아오는 곳은 분리하는게 좋아보이네요! 👍

2024-08-25 16:07 UTC, heedoitdox commented on di/src/main/java/com/interface21/context/support/AnnotationConfigWebApplicationContext.java
> +        Map<Class<?>, BeanDefinition> configurationBeanDefinitionMap = new ConfigurationBeanScanner(configurationClasses).scan();
개선해보겠습니다!

2024-08-25 16:08 UTC, heedoitdox commented on di/src/main/java/com/interface21/beans/factory/config/GenericBeanDefinition.java
> +  private final String beanName;
제가 바꾸다 말았나봐요 .. ㅎㅎ beanClassName 으로 통일하겠습니다!

2024-08-25 16:31 UTC, heedoitdox commented on di/src/main/java/com/interface21/beans/factory/support/SimpleBeanDefinitionRegistry.java
> +    Arrays.stream(maps).forEach(beanDefinitionMap::putAll);
헉!! 
그럴수있겠네요 당장 수정하겠습니다!

2024-08-26 15:23 UTC, shared-moon approved these changes
영빈님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
코멘트를 하나 남겨 뒀는데, 확인 후 다음 미션 진행 부탁드려요!
고생 많으셨습니다!

2024-08-26 15:23 UTC, shared-moon commented on di/src/main/java/com/interface21/beans/factory/support/SimpleBeanDefinitionRegistry.java
> +          validateExistBeanName(beanDefinition);
👍 
요건 약간 다른얘긴데, 개인적으로 stream을 사용 할 때의 최대장점이 선언형을 사용할 수 있게 되면서 가독성을 얻는것이라고 생각하는데요, 요렇게 어떻게 하는지 다 나열하는것보다 메서드로 한번 빼서 무엇을 하는지를 더 메인으로 드러내주면 어떨까요 ?

2024-08-26 15:23 UTC, merged