🚀 3단계 - @Configuration 구현하기
next-step/java-di pull request #47
Opened 2024-08-27 06:37 UTC by gutenLEE

안녕하세요, 한솔님!

3단계 미션을 진행하면서 2단계 미션에서 의존성 주입할 인자를 추출 및 추상화 작업도 진행해봤습니다!

이번 리뷰도 잘 부탁드립니다!

2024-08-27 06:52 UTC, gutenLEE commented on di/src/main/java/com/interface21/beans/factory/support/ConfigurationBeanDefinition.java
일반 Bean과 Configuration 구성 클래스의 팩토리 메서드용 BeanDefinition을 분류해봤습니다!

```mermaid
classDiagram
direction BT
class AnnotationBeanDefinition
class BeanDefinition {
<<Interface>>

}
class ConfigurationBeanDefinition

AnnotationBeanDefinition  ..>  BeanDefinition 
ConfigurationBeanDefinition  ..>  BeanDefinition 

```

2024-08-27 06:52 UTC, gutenLEE commented on di/src/main/java/com/interface21/beans/factory/support/ConfigurationBeanDefinitionScanner.java
>      private void registerBeanDefinitions(Set<Class<?>> configurationClasses) {
구성 클래스는 구성 클래스 빈 메타정보, 구성 클래스에 속한 `@Bean` 팩토리 메서드 메타정보를 로드해야 해서 두 번 스캔 작업하게 했습니다. 

- ` registerDeclaringClass(configurationClasses);`
- `registerBeanMethod(configurationClasses);`

`registerDeclaringClass()` 메서드에서 `AnnotationBeanDefinition`을 의존하고 있어 애초에 빈 정의 설계를 잘못 한 느낌도 드네요..

2024-08-27 06:52 UTC, gutenLEE commented on di/src/main/java/com/interface21/beans/factory/support/DefaultListableBeanFactory.java
> +            return autowireStrategy.autowire(beanDefinition, this);
의존성 주입할 인자 추출을 아예 의존성 주입 전략으로 추상화해봤습니다!

2024-08-27 09:45 UTC, catsbi requested changes
유희님 3단계 구현 잘 해주셨어요. 인터페이스 설계를 시도하고 전략패턴을 고려해주신 것 같네요! 
그런데 현재 설정 영역에서 애노테이션 기반의 컴포넌트들을 어떻게 등록하는지에 대해서 코멘트를 남긴게 했으니 확인 후 다시 리뷰요청 부탁드려요!

2024-08-27 09:45 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/config/AutowireStrategy.java
> +public interface AutowireStrategy {
자동연결 전략이라는 인터페이스명이 적절할까요 🤔 
Autowire 즉 자동 주입은 애노테이션기반으로 사용하는 측에서 선언시 자동으로 주입될 것을 기대하는 것이고, 
실제로 주입하는 측은 자동으로 해주는게 아니라 직접 로직을 통해 주입해주는 것이기 때문에 Injection 관련된명칭이 들어가는게 적절하지 않을까 싶네요!

2024-08-27 09:45 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/config/ConstructorAutowireStrategy.java
> +    public Object autowire(BeanDefinition beanDefinition, BeanFactory beanFactory) {
autowire라는 함수명보다는 주입을 의미하는 Inject가 더 적절하지 않을까요!

2024-08-27 09:45 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/support/ConfigurationBeanDefinition.java
이미지 자료까지 첨부해주시니 한결 알아보기 좋네요!

2024-08-27 09:45 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +        final Reflections reflections = new Reflections(STEREOTYPE_PACKAGE, basePackages);
STEREOTYPE_PACKAGE은 패키지를 옮길 경우 대응이 수동으로 되야하는데, 보통 스캐너의 기본 스캔 정책은 현재 클래스의 위치를 기반으로 하위 경로들을 스캔하기에 이를 활용해 정적이 아닌 동적으로 현재 스캐너의 위치를 구해서 전달하는게 낫지 않을까요?

2024-08-27 09:45 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/support/ConfigurationBeanDefinition.java
> +        return new FactoryMethodAutowireStrategy();
FactoryMethodAutowireStrategy는 무상태 객체로 보이는데 싱길톤 패턴을 적용해봐도 좋지 않을까요?

2024-08-27 09:45 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/support/ConfigurationBeanDefinitionScanner.java
>      private void registerBeanDefinitions(Set<Class<?>> configurationClasses) {
registerDeclaringClass이건 좀 애매하네요. 애노테이션기반의 빈 스캐너가 빈 스캔시 이 설정파일의 autowired 되야 할 빈들도 같이 포함시킬텐데 여기서 별도로 두 번 호출할 필요는 없을 것 같네요!

2024-08-28 05:25 UTC, gutenLEE commented on di/src/main/java/com/interface21/beans/factory/config/AutowireStrategy.java
> +public interface AutowireStrategy {
아하 어노테이션만 생각한 네이밍이었네요. 감사합니다.

2024-08-28 06:39 UTC, gutenLEE reviewed
피드백 반영했습니다!

2024-08-28 06:39 UTC, gutenLEE commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +    private static List<Class<? extends Annotation>> beanAnnotations = List.of(Component.class, Service.class, Controller.class, Repository.class, Configuration.class);
컨피그 빈 정보 스캔은 `AnnotationBeanDefinitionReader`가 
컨피그 빈에 선언된 @Bean 빈 정보 스캔은 `ConfigrationBeanDefinitionReader`가 하도록 변경했습니다!

2024-08-28 14:03 UTC, catsbi approved these changes
유희님 피드백 반영하시느라 고생 많으셨습니다!. 
큰 문제 없어보이니 다음 단계 진행해주세요!.

2024-08-28 14:03 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/support/BeanScanner.java
> +    private static List<Class<? extends Annotation>> beanAnnotations = List.of(Component.class, Service.class, Controller.class, Repository.class, Configuration.class);
정적으로 정의된 컬렉션 상수라면 상수 네이밍 컨벤션을 따라도 괜찮을 것 같네요!

2024-08-28 14:03 UTC, catsbi commented on di/src/main/java/com/interface21/beans/factory/support/InjectionType.java
> +    ;
콤마는 필요 없어보이네요!

2024-08-28 14:03 UTC, merged